export const schemaPresets = {
  user: {
    id: "string.uuid",
    firstName: "person.firstName",
    lastName: "person.lastName",
    fullName: "person.fullName",
    username: "internet.username",
    email: "internet.email",
    phone: "phone.number",
    age: "number.int",
    address: "location.streetAddress",
    city: "location.city",
    state: "location.state",
    country: "location.country",
    zipcode: "location.zipCode",
    avatar: "image.avatar",
    company: "company.name",
    jobTitle: "person.jobTitle",
    bio: "person.bio",
    createdAt: "date.anytime",
  },

  blogPost: {
    id: "string.uuid",
    title: "lorem.sentence",
    slug: "lorem.slug",
    excerpt: "lorem.paragraph",
    content: "lorem.paragraphs",
    authorName: "person.fullName",
    authorEmail: "internet.email",
    authorAvatar: "image.avatar",
    publishedAt: "date.anytime",
  },

  ecommerce: {
    id: "string.uuid",
    productName: "commerce.productName",
    description: "commerce.productDescription",
    price: "commerce.price",
    currencyCode: "finance.currencyCode",
    sku: "string.uuid",
    category: "commerce.department",
    image: "image.url",
    inStock: "datatype.boolean",
    createdAt: "date.anytime",
  },

  socialPost: {
    id: "string.uuid",
    content: "lorem.text",
    authorName: "person.fullName",
    authorUsername: "internet.username",
    authorAvatar: "image.avatar",
    likes: "number.int",
    commentsCount: "number.int",
    shares: "number.int",
    createdAt: "date.anytime",
  },

  analytics: {
    id: "string.uuid",
    eventName: "lorem.word",
    userId: "string.uuid",
    sessionId: "string.uuid",
    url: "internet.url",
    referrer: "internet.url",
    country: "location.country",
    city: "location.city",
    browser: "internet.userAgent",
    os: "system.semver",
    views: "number.int",
    clicks: "number.int",
    conversions: "number.int",
    createdAt: "date.anytime",
  },
} as const;

export type SchemaPresetType = keyof typeof schemaPresets;